name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: packed-solutions/con_Core.zip
          solution-folder: solutions/con_Core/src
          solution-type: Both
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          path: packed-solutions
